friends/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.autodiscover()

urlpatterns = [
    url(r'^', include('website.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

membership/models.py
from collections import OrderedDict

from django.db import models
from django.core.validators import (
    validate_email,
    RegexValidator,
    MinLengthValidator,
    MaxLengthValidator,
)
from django.utils import timezone

phone_validators = [
    RegexValidator(regex=r'^\d{10}$', message="Please enter a ten-digit phone number.")
]
zip_validators = [
    RegexValidator(regex=r'^\d{5}$', message="Please enter a five-digit ZIP code."),
]

class MemberManager(models.Manager):
    def active_members(self):
        member_ids = [member.id for member in self.all() if member.family.is_active()]
        return self.filter(pk__in=member_ids)
    def dues_counts(self):
        dues = [member.family.dues_amount for member in self.all() if member.family.is_active()]
        return {i:len([d for d in dues if d == i]) for i in set(dues)}

class FamilyManager(models.Manager):
    def total_dues_fiscal_year(self):
        return sum(family.dues_amount for family in self.all() if family.paid_this_fiscal_year())
    def total_dues_prev_12mo(self):
        return sum(family.dues_amount for family in self.all() if family.is_active())
    def dues_counts(self):
        dues = [family.dues_amount for family in self.all() if family.is_active()]
        return {i:len([d for d in dues if d == i]) for i in set(dues)}

class Family(models.Model):
    objects = FamilyManager()
    family_name = models.CharField(max_length=200)
    family_name_2 = models.CharField(max_length=200, blank=True, verbose_name='Alternative family name')
    street_address_1 = models.CharField(max_length=200, blank=True)
    street_address_2 = models.CharField(max_length=200, blank=True)
    zip_code = models.CharField(max_length=5, blank=False, validators=zip_validators)
    home_phone = models.IntegerField(
        validators=phone_validators,
        blank=True,
        null=True,
    )
    last_paid = models.DateField(verbose_name="date dues paid")
    dues_amount = models.PositiveSmallIntegerField()
    comment = models.CharField(max_length=200, blank=True)
    def paid_this_fiscal_year(self):
        start_fiscal_year = timezone.now().date().replace(month=7)
        if start_fiscal_year > timezone.now().date():
            start_fiscal_year = start_fiscal_year.replace(year=timezone.now().year-1)
        return self.last_paid >= start_fiscal_year
    paid_this_fiscal_year.admin_order_field = last_paid
    paid_this_fiscal_year.boolean = True
    paid_this_fiscal_year.short_description = 'Dues paid this fiscal year?'
    def is_active(self):
        year_ago = timezone.now().date().replace(year=timezone.now().year-1)
        return self.last_paid >= year_ago
    is_active.admin_order_field = last_paid
    is_active.boolean = True
    is_active.short_description = 'Dues paid?'
    def is_grafton_resident(self):
        return self.zip_code in ('01519', '01536', '01560')
    is_grafton_resident.admin_order_field = zip_code
    is_grafton_resident.boolean = True
    is_grafton_resident.short_description = 'Grafton resident(s)?'
    def __str__(self):
        if self.family_name_2:
            return self.family_name + '/' + self.family_name_2
        return self.family_name

class Member(models.Model):
    objects = MemberManager()
    last_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    family = models.ForeignKey(Family)
    email = models.EmailField(blank=True, null=True, validators=[validate_email])
    personal_phone = models.IntegerField(
        validators=phone_validators,
        blank=True,
        null=True,
    )
    comment = models.CharField(max_length=200, blank=True)
    volunteer = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)
    trustee = models.BooleanField(default=False)
    @property
    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)
    def __str__(self):
        return self.full_name

class Committee(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    members = models.ManyToManyField(Member, through='Role')
    def __str__(self):
        return self.name

class Role(models.Model):
    committee = models.ForeignKey(Committee, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50)
    def __str__(self):
        return "%s, %s" % (self.member.__str__(), self.title)
    def __key__(self):
        role_order = OrderedDict([
            ('president', 0),
            ('secretary', 1),
            ('treasurer', 2),
            ('director', 1000),
            ('chair', 2000),
            ('member', 3000),
        ])
        key = role_order.get(self.title.lower())
        if key is None:
            for ro in role_order:
                if ro in self.title.lower():
                    key = role_order.get(ro) + 0.0001
                    break
        if key is None:
            key = 1000000
        return key
    def __lt__(self, other):
        return self.__key__() < other.__key__()

friends/views.py
from django.shortcuts import render

from membership.models import Committee

def home(request):
    return render(request, 'friends/home.html')

def about(request):
    committees = Committee.objects.all()
    context = {'committees': committees}
    return render(request, 'friends/about.html', context)

def contact(request):
    return render(request, 'friends/contact.html')

def downunder(request):
    return render(request, 'friends/downunder.html')

def join(request):
    return render(request, 'friends/join.html')

templates/friends/about.html
{% extends "friends/base.html" %}
    {% block body %}
        <div class="row row-content about">
            <div class="col-xs-12">
                <h1>{% block title %}About{% endblock %} The Friends</h1>
                <p>
                    The Friends of the Grafton Public Library is a volunteer organization that works to support our library through advocacy and activities designed to raise money for library needs which are not funded by our local, state or federal government.
                </p>
                <p>
                    We use the money we raise from the <a href="{% url 'downunder' %}">Down Under Bookstore</a>, fundraisers, and <a href="{% url 'join' %}">memberships</a> to offer a variety of programs to the Grafton community. These programs include museum passes, the summer reading program, exhibits, speakers, workshops, and concerts.
                </p>
            </div>
        </div>
        <div class="row row-content about">
            <div class="col-xs-12">
                <h2>Committees</h2>
                <p>There are several ways to get involved with the Friends.  In addition to volunteering at individual events, you can serve on our of our committees.  If you're interested joining a committee, just <a href="{% url 'contact' %}">let us know</a>.
            </div>
            {% for committee in committees %}
            <div class="col-xs-12 col-sm-6">
                <h3>{{ committee.name }}</h3>
                <p>{{ committee.description }}</p>
                <div class="table-responsive">
                    <table class="table">
                        <colgroup>
                            <col class="col-xs-4">
                            <col class="col-xs-4">
                        </colgroup>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                        </tr>
                        {% for role in committee.role_set.all %}
                        <tr>
                            <td>{% firstof role.member.full_name "VACANT" %}</td>
                            <td>{{ role.title }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
            {% endfor %}
        </div>
    {% endblock %}

templates/friends/base.html
{% load static %}
<html>
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css" rel="stylesheet">
    {% load compress %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'main.scss' %}" type="text/x-scss" charset="utf-8">
    {% endcompress %}
    <title>
      Friends of the Grafton Public Library - {% block title %}{% endblock %}
    </title>
  </head>
  <body>
{% include "friends/header.html" %}
{% block jumbotron %}{% endblock %}
    <div class="container content">
{% block body %}{% endblock %}
    </div>
{% include "friends/footer.html" %}
  </body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

templates/friends/contact.html
{% extends "friends/base.html" %}
    {% block body %}
        <div class="row row-content about">
            <div class="col-xs-12">
                <h1>{% block title %}Contact Us{% endblock %}</h1>
                <p>
                    The best way to contact us is via email: <a href="mailto:info@friendsgpl.org">info@friendsgpl.org</a>.  You can also message us or post on our <a href="https://www.facebook.com/GPLFriends">Facebook page</a>.  If you're old school, you can send mail to:
                </p>
                <p>
                    Friends of the Grafton Public Library<br>
                    PO Box 387<br>
                    Grafton, MA 01519
                </p>
            </div>
        </div>
    {% endblock %}

templates/friends/downunder.html
{% extends "friends/base.html" %}
    {% block body %}
        <div class="row row-content">
            <div class="col-xs-12">
                <h1>{% block title %}Down Under Bookstore{% endblock %}</h1>
                <p>
                    The Friends of the Grafton Public Library operate the Down Under Bookstore in the lower level of the Main Library. The Down Under Book Store is open the same hours as the Library. Books, CDs, videos, and paperbacks for adults are $1.00 each. Children’s books are four for $1.00. You will also find videotapes, books on tape, DVDs, and CDs. In the Main Reading Room, near the Friends Cafe, we sometimes offer current books in pristine condition for $3. At holiday time, we offer gift collections for $5-$10 dollars. You will find a wide range of books, both fiction and nonfiction:
                </p>
                <ul>
                    <li>
                        Classics
                    </li>
                    <li>
                        Mysteries
                    </li>
                    <li>
                        Children’s books
                    </li>
                    <li>
                        Science fiction
                    </li>
                    <li>
                        Cooking
                    </li>
                    <li>
                        Crafts
                    </li>
                    <li>
                        Self-help
                    </li>
                    <li>
                        Parenting
                    </li>
                    <li>
                        Travel
                    </li>
                    <li>
                        Reference
                    </li>
                </ul>
                <p>
                    The proceeds from Down Under support the Friends’ Museum Pass program and the many programs sponsored by the Friends. Donations to the Down Under Bookstore are most welcome. Donated gently used books, CDs, or videos should be in good, unmarked, saleable condition. Magazines, textbooks, Reader’s Digest Condensed Books, and outdated, old or ugly books are not useful, and the Friends ask to be saved the trouble and expense of disposing of them. Moldy books are unacceptable. Donations may be left in the plastic bins at the bottom of the stairs near the bookstore. Please do not put donations in the book drops.
                </p>
            </div>
        </div>
    {% endblock %}

templates/friends/footer.html
    <footer class="footer">
        <div class="row row-footer">
            <div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 col-lg-4 col-lg-offset-2">
                <div class="row">
                    <div class="col-xs-4">
                        <h5>Pages</h5>
                        <ul class="list-unstyled">
                            {% include "friends/nav_list.html" %}
                        </ul>
                    </div>
                    <div class="col-xs-8">
                        <h5>Address</h5>
                        <address>
                            Friends of the Grafton Public Library<br>
                            PO Box 387<br>
                            Grafton MA 01519<br>
                            <a href="mailto:info@friendsgpl.org">info@friendsgpl.org</a>
                        </address>
                    </div>
                </div>
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 col-lg-4">
                <div class="row">
                    <div class="col-xs-4 col-lg-6">
                        <h5>Wrong Grafton?  Try one of these:</h5>
                        <ul class="list-unstyled">
                            <li>
                                <a href="http://www.townofgraftonnh.com/aboutus/graftonpubliclibrary.html">New Hampshire</a>
                            </li>
                            <li>
                                <a href="http://www.graftonpubliclibrary.net/">Wisconsin</a>
                            </li>
                            <li>
                                <a href="http://www.crl.nsw.gov.au/clarence-valley-libraries/grafton-library/">New South Wales</a>
                            </li>
                            <li>
                                <a href="http://libguides.marybaldwin.edu/home">Mary Baldwin University</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-8 col-lg-6">
                        <h5>Social Media</h5>
                        <div class="nav navbar-nav">
                            <a class="btn btn-block btn-social btn-facebook" href="https://www.facebook.com/Friends-of-the-Grafton-Public-Library-203738076330695" target="_blank"><span class="fa fa-facebook"></span> Like the Friends on Facebook!</a>
                            <a class="btn btn-block btn-social btn-facebook" href="https://www.facebook.com/GraftonPublicLibraryMA/" target="_blank"><span class="fa fa-facebook"></span> Like the library on Facebook!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/friends/header.html
{% load static %}
    <header class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" ui-sref="app"><img src="{% static 'images/logo_no_words.png' %}"></a>
                <h3>Friends of the GPL</h3>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav nav-pills pull-xs-left pull-sm-and-up-right">
                    {% include "friends/nav_list.html" %}
                </ul>
            </div>
        </nav>
    </header>

templates/friends/home.html
{% extends "friends/base.html" %}
{% load static %}
    {% block jumbotron %}
        <div class="jumbotron">
            <div class="container">
                <div class="row row-header">
                    <div class="col-xs-12 col-sm-3 col-sm-push-9">
                        <img class="img-responsive" src="{% static 'images/logo_no_words.png' %}" alt="Logo for the Friends of the Grafton Public Library">
                    </div>
                    <div class="col-xs-12 col-sm-9 col-sm-pull-3">
                        <h1>{% block title %}Welcome{% endblock %}, Friend!</h1>
                        <p class="lead">The Friends of the Grafton Public Library: Providing volunteer and fundraising support to the Grafton Public Library in Grafton, MA.</p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
    {% block body %}
        <article class="row row-content">
            <section class="col-xs-12 col-sm-4 col-md-5 col-lg-6">
                <article>
                    <h1>Who are the Friends?</h1>
                    <p>The Friends of the Grafton Public Library is a volunteer organization that works to support our library through advocacy and activities designed to raise money for library needs which are not funded by our local, state, or federal government.</p>
                    <p>We use the money we raise from the Down Under Bookstore, fundraisers, and memberships to offer a variety of programs to the Grafton community. These programs include museum passes, the summer reading program, exhibits, speakers, workshops, and concerts.</p>
                    <p>For more info, see our <a href="{% url 'about' %}">about us</a> page.</p>
                </article>
                <article>
                    <h1>We're Selling Tote Bags</h1>
                    <p>Come and get a fabulous tote bag - it’s large, washable and has two pockets, including a zipper pocket perfect for holding a Library card or attaching a key chain.  They come in three color options, khaki with forest green embroidery, khaki with lime green embroidery, and poppy with navy embroidery.</p>
                    <p>Bags are going for $20, but members of the Friends get them for $18.  All proceeds benefit the Grafton Public Library.  Stop by the library and get yours today!</p>
                    <section class="row">
                        <section class="col-xs-6 col-sm-12 col-lg-6">
                            <a href="{% static 'images/all_bags.jpg' %}">
                            <div class="thumbnail">
                                <img src="{% static 'images/all_bags.jpg' %}" class="img-responsive" alt="Three tote bags">
                                <div class="caption">
                                    <p>Tote bags in all three color options.  Click for full size.</p>
                                </div>
                            </div>
                            </a>
                        </section>
                        <section class="col-xs-6 col-sm-12 col-lg-6">
                            <a href="{% static 'images/khaki_bag.jpg' %}">
                            <div class="thumbnail">
                                <img src="{% static 'images/khaki_bag.jpg' %}" class="img-responsive" alt="Tan tote bag">
                                <div class="caption">
                                    <p>Example of the khaki bag filled with stuff.  Click for full size.</p>
                                </div>
                            </div>
                            </a>
                        </section>
                    </section>
                </article>
            </section>
            <section class="col-xs-12 col-sm-8 col-md-7 col-lg-6">
                <h1>News and Events</h1>
                <p>To see what we're up to, use our Facebook page plugin below.  For upcoming events, check the events tab.  For recent news, check the timeline tab.</p>
                <div class="fb-page" data-href="https://www.facebook.com/GPLFriends/" data-tabs="events, timeline" data-height="600" data-width="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                    <blockquote cite="https://www.facebook.com/GPLFriends/" class="fb-xfbml-parse-ignore">
                        <a href="https://www.facebook.com/GPLFriends/">Friends of the Grafton Public Library</a>
                    </blockquote>
                </div>
            </section>
        </article>

        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    {% endblock %}

templates/friends/join.html
{% extends "friends/base.html" %}
{% load static %}
    {% block body %}
        <div class="row row-content join">
            <div class="col-xs-12">
                <h1>{% block title %}Join the Friends{% endblock %}</h1>
                <p>You can download and print the <a href="{% static 'misc_docs/friendsgpl_membership_form_2016.docx' %}">membership form</a> and submit it with a check via snail mail (all info including address is on the form), or fill out the internet form below and pay securely via Paypal.</p>
                <p>If you're already a member, you can use the same form or paypal links to renew. If you're unsure if your membership is up to date, <a href="{% url 'contact' %}">contact us</a>.</p>
                <div class="row">
                    <div class="col-sm-6 col-md-5 col-lg-4">
                        <div class="btn-group-vertical btn-block">
                            <label>Membership Level</label>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8BNZZ2SXUEMSG">Senior/Student - $5</a>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NJL4GYAWP68JG">Individual - $10</a>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=N7MGEXBATZCW2">Family - $25</a>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZTSMKFAZUS3BU">Best Friend - $100</a>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZZWWQZFRNHQNL">Business - $250</a>
                            <a class="btn btn-default" role="button" target="_blank" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=U8JTRKPYAKZXA">Other - enter amount on next page</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}